default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_collection_development

test:
  <<: *default
  database: book_collection_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: book_collection_production
  username: book_collection
  password: <%= ENV['BOOK_COLLECTION_DATABASE_PASSWORD'] %>

  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    database: book_collection_queue
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    url: <%= ENV['CACHE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    database: book_collection_cache
    migrations_paths: db/cache_migrate

  cable:
    <<: *default
    url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    database: book_collection_cable
    migrations_paths: db/cable_migrate