# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  # options courtecy of https://stackoverflow.com/questions/19486429/working-on-a-rails-app-locally-with-a-remote-postgres-connection
  # host: "kiwi"
  # port: 38787
  # encoding: unicode
  # username: shlok
  url: postgres://u7bvbpto5alv3s:p1d01d27a71d92c73e38bf22ed05a675431889920a9b181aedb67c6e9bc0d41be@c3nv2ev86aje4j.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d1573uomgqud72 
  # password: shlok
  pool: 5


development:
  <<: *default
  database: devdb11
test:
  <<: *default
  database: testdb11
production:
  <<: *default
  database: prod11
cable:
<<: *production
database: storage/production_cable
cache:
<<: *production
database: storage/production_cache
queue:
<<: *production
database: storage/production_queue