default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_collection_development

test:
  <<: *default
  database: book_collection_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: book_collection_production
  username: book_collection
  password: <%= ENV['BOOK_COLLECTION_DATABASE_PASSWORD'] %>

# Additional configurations for cache, queue, and cable
cache:
  <<: *default
  database: book_collection_cache
  migrations_paths: db/cache_migrate

queue:
  <<: *default
  database: book_collection_queue
  migrations_paths: db/queue_migrate

cable:
  <<: *default
  database: book_collection_cable
  migrations_paths: db/cable_migrate
